// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';
import vercel from '@astrojs/vercel';

export default defineConfig({
  site: 'https://luciolle.fr',
  output: 'server',
  adapter: vercel(),
  integrations: [sitemap()],
  vite: {
    plugins: [tailwindcss()],
  },
  redirects: {
    '/blog/aide-personnalisee-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/alternatives-cahier-journal-numerique': '/blog/cahier-journal-papier-vs-numerique',
    '/blog/applications-enseignants-maternelle': '/blog/cahier-journal-maternelle',
    '/blog/avantages-cahier-journal-numerique': '/blog/cahier-journal-papier-vs-numerique',
    '/blog/bien-etre-enseignant-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/burn-out-enseignant-solutions': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-de-textes-numerique': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-arts': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-ce1': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-ce1-exemple': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-ce2': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-cp-exemple': '/blog/cahier-journal-cp',
    '/blog/cahier-journal-cycle-2': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-cycle-3': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-debutant-enseignant': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-efficient': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-emploi-du-temps': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-eps': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-excel': '/blog/cahier-journal-papier-vs-numerique',
    '/blog/cahier-journal-fiche-de-prep': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-francais': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-gratuit': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-histoire-geo': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-inspection': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-inspection-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-maternelle-organisation': '/blog/cahier-journal-maternelle',
    '/blog/cahier-journal-maths': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-ms': '/blog/cahier-journal-maternelle',
    '/blog/cahier-journal-numérique-2026': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-obligations-legales': '/blog/cahier-journal-numerique-enseignant',
    '/blog/cahier-journal-progressions': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-remplacement': '/blog/cahier-journal-enseignant-remplacant',
    '/blog/cahier-journal-sciences': '/blog/modele-cahier-journal-primaire',
    '/blog/cahier-journal-word': '/blog/cahier-journal-papier-vs-numerique',
    '/blog/calcul-mental-primaire-conseils': '/blog/modele-cahier-journal-primaire',
    '/blog/calendrier-scolaire-enseignant': '/blog/rentree-scolaire-enseignant-checklist',
    '/blog/classe-inclusive-organisation': '/blog/cahier-journal-ulis',
    '/blog/comment-faire-cahier-journal': '/blog/cahier-journal-numerique-enseignant',
    '/blog/communication-parents-enseignant': '/blog/cahier-journal-numerique-enseignant',
    '/blog/competences-socle-commun-primaire': '/blog/nouveaux-programmes-primaire-2026',
    '/blog/conseil-de-classe-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/conseil-des-maitres-organisation': '/blog/cahier-journal-numerique-enseignant',
    '/blog/debut-annee-scolaire-conseils': '/blog/rentree-scolaire-enseignant-checklist',
    '/blog/dictee-primaire-organisation': '/blog/modele-cahier-journal-primaire',
    '/blog/difference-cahier-journal-cahier-de-prep': '/blog/cahier-journal-numerique-enseignant',
    '/blog/fin-annee-scolaire-bilan': '/blog/cahier-journal-numerique-enseignant',
    '/blog/formation-enseignant-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/gagner-du-temps-cahier-journal': '/blog/cahier-journal-numerique-enseignant',
    '/blog/imprimer-cahier-journal': '/blog/cahier-journal-numerique-enseignant',
    '/blog/inclure-eleves-dys-primaire': '/blog/cahier-journal-ulis',
    '/blog/inconvenients-cahier-journal-numerique': '/blog/cahier-journal-papier-vs-numerique',
    '/blog/lecture-cp-progression': '/blog/cahier-journal-cp',
    '/blog/livret-scolaire-numerique': '/blog/cahier-journal-numerique-enseignant',
    '/blog/logiciel-cahier-journal': '/blog/cahier-journal-numerique-enseignant',
    '/blog/luciolle-vs-edumoov': '/blog/cahier-journal-papier-vs-numerique',
    '/blog/luciolle-vs-teetsh': '/blog/cahier-journal-papier-vs-numerique',
    '/blog/meilleur-outil-cahier-journal': '/blog/cahier-journal-numerique-enseignant',
    '/blog/modele-cahier-journal-journee': '/blog/modele-cahier-journal-primaire',
    '/blog/modele-cahier-journal-semaine': '/blog/modele-cahier-journal-primaire',
    '/blog/noter-les-eleves-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/organiser-semaine-enseignant': '/blog/cahier-journal-numerique-enseignant',
    '/blog/outils-gestion-classe-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/outils-numeriques-enseignants-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/planifier-cours-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/ppre-enseignant-primaire': '/blog/cahier-journal-ulis',
    '/blog/preparer-classe-decouverte': '/blog/cahier-journal-numerique-enseignant',
    '/blog/preparer-rentree-enseignant': '/blog/rentree-scolaire-enseignant-checklist',
    '/blog/programmation-annuelle-maternelle': '/blog/cahier-journal-maternelle',
    '/blog/progression-annuelle-primaire': '/blog/modele-cahier-journal-primaire',
    '/blog/projet-classe-primaire-organisation': '/blog/cahier-journal-numerique-enseignant',
    '/blog/reunion-parents-enseignant-conseils': '/blog/cahier-journal-numerique-enseignant',
    '/blog/rituels-maternelle-organisation': '/blog/cahier-journal-maternelle',
    '/blog/semaine-type-enseignant': '/blog/cahier-journal-numerique-enseignant',
    '/blog/sortie-scolaire-organisation': '/blog/cahier-journal-numerique-enseignant',
    '/blog/tableau-numerique-interactif-primaire': '/blog/cahier-journal-numerique-enseignant',
    '/blog/temps-preparation-cours-enseignant': '/blog/cahier-journal-numerique-enseignant',
    '/blog/tice-primaire-enseignant': '/blog/cahier-journal-numerique-enseignant',
    '/blog/travaux-pratiques-maternelle': '/blog/cahier-journal-maternelle',
    '/blog/tutoriel-cahier-journal-numerique': '/blog/cahier-journal-numerique-enseignant',
    '/blog/vacances-scolaires-2026': '/blog/rentree-scolaire-enseignant-checklist',
  },
});
